In [3]:
from google.colab import files

uploaded = files.upload()

Saving coretech_clients_cleaned.csv to coretech_clients_cleaned (1).csv

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [5]:
df = pd.read_csv("coretech_clients_cleaned.csv")

df.head()

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,1,Ali Khan,ABC Tech,Web Development,5000,30,Lahore,Facebook,Completed,4.5
1,2,Sara Ahmed,Digital Hub,AI Solutions,7000,45,Karachi,Website,Active,4.8
2,3,Usman Malik,TechNova,Data Science,6500,40,Islamabad,LinkedIn,Completed,4.6
3,4,Ayesha Noor,SoftVision,Cloud Computing,8000,60,Lahore,Referral,Active,4.7
4,5,Hamza Ali,FutureTech,Mobile App,5500,35,Faisalabad,Facebook,Completed,4.3

In [6]:
X = df[
[
"service",
"project_duration_days",
"client_city",
"lead_source",
"rating",
"project_budget"
]
]


y = df["status"]

In [7]:
categorical_features = [
"service",
"client_city",
"lead_source"
]


numerical_features = [
"project_duration_days",
"rating",
"project_budget"
]

In [8]:
preprocessor = ColumnTransformer(

transformers=[

(
"categorical",
OneHotEncoder(handle_unknown="ignore"),
categorical_features
)

],

remainder="passthrough"

)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(

X,
y,
test_size=0.2,
random_state=42

)


print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (24, 6)
Testing: (6, 6)

In [10]:
model = Pipeline(

steps=[

("preprocessor", preprocessor),

("classifier",
 RandomForestClassifier(
     n_estimators=100,
     random_state=42
 ))

]

)


model.fit(
X_train,
y_train
)


print("Model Trained Successfully")

Model Trained Successfully

In [11]:
predictions = model.predict(X_test)

print(predictions)

['Active' 'Active' 'Completed' 'Completed' 'Active' 'Completed']

In [12]:
result = pd.DataFrame({

"Actual_Status": y_test,

"Predicted_Status": predictions

})


result.to_csv(
"predictions_status.csv",
index=False
)


result

   Actual_Status Predicted_Status
27     Completed           Active
15     Completed           Active
23     Completed        Completed
17     Completed        Completed
8         Active           Active
9      Completed        Completed

In [13]:
accuracy = accuracy_score(
y_test,
predictions
)


print(
"Accuracy:",
accuracy
)

Accuracy: 0.6666666666666666

In [14]:
cm = confusion_matrix(
y_test,
predictions
)

print("Confusion Matrix:")

print(cm)
report = classification_report(
y_test,
predictions
)

print(report)

Confusion Matrix:
[[1 0]
 [2 3]]
              precision    recall  f1-score   support

      Active       0.33      1.00      0.50         1
   Completed       1.00      0.60      0.75         5

    accuracy                           0.67         6
   macro avg       0.67      0.80      0.62         6
weighted avg       0.89      0.67      0.71         6

In [15]:
print("===== MODEL PERFORMANCE =====")

print(
"Accuracy Score:",
accuracy
)


print("\nConfusion Matrix:")

print(cm)


print("\nClassification Report:")

print(report)

===== MODEL PERFORMANCE =====
Accuracy Score: 0.6666666666666666

Confusion Matrix:
[[1 0]
 [2 3]]

Classification Report:
              precision    recall  f1-score   support

      Active       0.33      1.00      0.50         1
   Completed       1.00      0.60      0.75         5

    accuracy                           0.67         6
   macro avg       0.67      0.80      0.62         6
weighted avg       0.89      0.67      0.71         6

In [16]:
from google.colab import files

files.download("predictions_status.csv")